### ISSUE TITLE
New GitHub User for authentication

### ISSUE THREAD

**Issue by mattBrzezinski** [invenia/KeepActionsAlive#3]
We need to create a new GitHub user where we can add it to all organizations where we maintain open source code, from there we can generate a PAT token which has access to re-enable workflows in that organization.

**Comment by iamed2** [comment]
Should be added to the https://github.com/orgs/invenia/teams/automatons group

**Comment by mattBrzezinski** [comment]
Created the account https://github.com/InveniaBot.
